package X;

/* renamed from: X.050  reason: invalid class name */
/* loaded from: classes.dex */
public abstract class AnonymousClass050 {
    public static final Integer A00 = 0;
    public static final Integer A01;
    public static final Integer A02;
    public static final Integer A03;
    public static final Integer A04;
    public static final Integer A05;
    public static final Integer A06;
    public static final Integer A07;
    public static final Integer A08;
    public static final Integer A09;
    public static final Integer A0A;
    public static final Integer A0B;
    public static final Integer A0C;
    public static final Integer A0D;
    public static final Integer A0E;
    public static final Integer A0F;
    public static final Integer A0G;
    public static final Integer A0H;
    public static final Integer A0I;
    public static final Integer A0J;
    public static final Integer A0K;
    public static final Integer A0L;
    public static final Integer A0M;
    public static final Integer A0N;
    public static final Integer A0O;
    public static final Integer A0P;
    public static final Integer A0Q;
    public static final Integer A0R;
    public static final Integer A0S;
    public static final Integer A0T;
    public static final Integer A0U;
    public static final Integer A0V;
    public static final Integer A0W;
    public static final Integer A0X;
    public static final Integer A0Y;
    public static final Integer A0Z;
    public static final Integer A0a;
    public static final Integer A0b;
    public static final Integer A0c;
    public static final Integer A0d;
    public static final Integer A0e;
    public static final Integer A0f;
    public static final Integer A0g;
    public static final Integer A0h;
    public static final Integer A0i;
    public static final Integer A0j;
    public static final Integer A0k;
    public static final Integer A0l;
    public static final Integer A0m;
    public static final Integer A0n;
    public static final Integer A0o;
    public static final Integer A0p;
    public static final Integer A0q;
    public static final Integer A0r;
    public static final Integer A0s;
    public static final Integer A0t;
    public static final Integer A0u;
    public static final Integer A0v;
    public static final Integer[] A0w;

    public static Integer[] A01(int i) {
        Integer[] numArr = new Integer[i];
        System.arraycopy(A0w, 0, numArr, 0, i);
        return numArr;
    }

    static {
        Integer[] numArr = new Integer[87];
        numArr[0] = 0;
        A01 = 1;
        numArr[1] = 1;
        A0C = 2;
        numArr[2] = 2;
        A0N = 3;
        numArr[3] = 3;
        A0V = 4;
        numArr[4] = 4;
        A0c = 5;
        numArr[5] = 5;
        A0l = 6;
        numArr[6] = 6;
        A0q = 7;
        numArr[7] = 7;
        A0s = 8;
        numArr[8] = 8;
        A0v = 9;
        numArr[9] = 9;
        A02 = 10;
        numArr[10] = 10;
        A03 = 11;
        numArr[11] = 11;
        A04 = 12;
        numArr[12] = 12;
        A05 = 13;
        numArr[13] = 13;
        A06 = 14;
        numArr[14] = 14;
        A07 = 15;
        numArr[15] = 15;
        A08 = 16;
        numArr[16] = 16;
        A09 = 17;
        numArr[17] = 17;
        A0A = 18;
        numArr[18] = 18;
        A0B = 19;
        numArr[19] = 19;
        A0D = 20;
        numArr[20] = 20;
        A0E = 21;
        numArr[21] = 21;
        A0F = 22;
        numArr[22] = 22;
        A0G = 23;
        numArr[23] = 23;
        A0H = 24;
        numArr[24] = 24;
        A0I = 25;
        numArr[25] = 25;
        A0J = 26;
        numArr[26] = 26;
        A0K = 27;
        numArr[27] = 27;
        A0L = 28;
        numArr[28] = 28;
        A0M = 29;
        numArr[29] = 29;
        A0O = 30;
        numArr[30] = 30;
        A0P = 31;
        numArr[31] = 31;
        A0Q = 32;
        numArr[32] = 32;
        A0R = 33;
        numArr[33] = 33;
        A0S = 34;
        numArr[34] = 34;
        A0T = 35;
        numArr[35] = 35;
        A0U = 36;
        numArr[36] = 36;
        A00(numArr, 37);
        A00(numArr, 38);
        A00(numArr, 39);
        A00(numArr, 40);
        A0W = 41;
        numArr[41] = 41;
        A00(numArr, 42);
        A00(numArr, 43);
        A0X = 44;
        numArr[44] = 44;
        A0Y = 45;
        numArr[45] = 45;
        A0Z = 46;
        numArr[46] = 46;
        A00(numArr, 47);
        A0a = 48;
        numArr[48] = 48;
        A0b = 49;
        numArr[49] = 49;
        A0d = 50;
        numArr[50] = 50;
        A0e = 51;
        numArr[51] = 51;
        A0f = 52;
        numArr[52] = 52;
        A0g = 53;
        numArr[53] = 53;
        A0h = 54;
        numArr[54] = 54;
        A00(numArr, 55);
        A00(numArr, 56);
        A0i = 57;
        numArr[57] = 57;
        A0j = 58;
        numArr[58] = 58;
        A0k = 59;
        numArr[59] = 59;
        A00(numArr, 60);
        A0m = 61;
        numArr[61] = 61;
        A00(numArr, 62);
        A00(numArr, 63);
        A0n = 64;
        numArr[64] = 64;
        A0o = 65;
        numArr[65] = 65;
        A00(numArr, 66);
        A0p = 67;
        numArr[67] = 67;
        A00(numArr, 68);
        A00(numArr, 69);
        A00(numArr, 70);
        A00(numArr, 71);
        A00(numArr, 72);
        A00(numArr, 73);
        A00(numArr, 74);
        A00(numArr, 75);
        A00(numArr, 76);
        A00(numArr, 77);
        A00(numArr, 78);
        A0r = 79;
        numArr[79] = 79;
        A0t = 80;
        numArr[80] = 80;
        A0u = 81;
        numArr[81] = 81;
        A00(numArr, 82);
        A00(numArr, 83);
        A00(numArr, 84);
        A00(numArr, 85);
        A00(numArr, 86);
        A0w = numArr;
    }

    public static void A00(Object[] objArr, int i) {
        objArr[i] = Integer.valueOf(i);
    }
}
