package X;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/* renamed from: X.02I  reason: invalid class name */
/* loaded from: classes.dex */
public abstract class C02I {
    public static final Set A00 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", "com.facebook.akira", "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.arstudio.player", "com.facebook.assistantplayground", "com.instagram.barcelona", "com.facebook.bishop", "com.facebook.pages.app", "com.facebook.creatorstudio", "com.facebook.daykira", "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.system.data", "com.facebook.wearable.apps.mwear", "com.facebook.wearable.system.notification", "com.facebook.wearable.monza", "com.oculus.assistant", "com.oculus.vrshell", "com.oculus.firsttimenux", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.vrshell.home", "com.oculus.ocms", "com.oculus.q4bservice", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.oculus.systemux", "com.oculus.companion.server", "com.facebook.bonfire", "com.facebook.stella", "com.facebook.stella_debug", "com.facebook.study", "com.facebook.wakizashi", "com.facebook.wearable.system.launcher", "com.whatsapp", "com.whatsapp.w4b", "com.facebook.work", "com.facebook.workdev", "com.facebook.workchat")));
    public static final Set A02 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", "com.facebook.akira", "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.arstudio.player", "com.facebook.assistantplayground", "com.instagram.barcelona", "com.facebook.bishop", "com.facebook.pages.app", "com.facebook.creatorstudio", "com.facebook.daykira", "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.monza", "com.oculus.assistant", "com.oculus.vrshell", "com.oculus.firsttimenux", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.vrshell.home", "com.oculus.ocms", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.oculus.systemux", "com.facebook.bonfire", "com.facebook.stella", "com.facebook.stella_debug", "com.facebook.study", "com.facebook.wakizashi", "com.whatsapp", "com.whatsapp.w4b")));
    public static final Set A01 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", "com.facebook.akira", "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.arstudio.player", "com.facebook.assistantplayground", "com.instagram.barcelona", "com.facebook.bishop", "com.facebook.pages.app", "com.facebook.creatorstudio", "com.facebook.daykira", "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.system.data", "com.facebook.wearable.apps.mwear", "com.facebook.wearable.system.notification", "com.facebook.wearable.monza", "com.oculus.assistant", "com.oculus.vrshell", "com.oculus.firsttimenux", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.vrshell.home", "com.oculus.ocms", "com.oculus.q4bservice", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.oculus.systemux", "com.oculus.companion.server", "com.facebook.bonfire", "com.facebook.stella", "com.facebook.stella_debug", "com.facebook.study", "com.facebook.wakizashi", "com.facebook.wearable.system.launcher", "com.whatsapp", "com.whatsapp.w4b")));
    public static final Set A05 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.work", "com.facebook.workdev", "com.facebook.workchat")));
    public static final Set A03 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.instagram.direct", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.instagram.barcelona")));
    public static final Set A04 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.oculus.assistant", "com.oculus.browser", "com.oculus.companion.server", "com.oculus.explore", "com.oculus.firsttimenux", "com.oculus.vrshell.home", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.nux.ota", "com.oculus.ocms", "com.oculus.updater", "com.oculus.q4bservice", "com.oculus.store", "com.oculus.systemux", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2")));
}
